[build]
target = "avr-none"
rustflags = ["-C", "target-cpu=atmega328p"]

[target.'cfg(target_arch = "avr")']
runner = "ravedude"

[unstable]
build-std = ["core"]

# To build for ATmega328PB instead, override RUSTFLAGS:
# RUSTFLAGS="-C target-cpu=atmega328pb" cargo build --release --no-default-features --features atmega328pb
